Docker Image
brunopdias/semanainvernogeofisica pull request #3
Opened 2020-05-08 23:53 UTC by cauachagas

Added python3 compatibility (tested in Manjaro Linux)
"Mhelm2D_fwi.c" (helm2D) works with Madagascar master-branch
Added a Dockerfile to build a container with the official Madagascar image + Octave.

2020-05-09 17:32 UTC, brunopdias requested changes
A API do pwsmooth realmente mudou. Mas creio que para funcionar corretamente, ainda seja necessária a inicialização (  pwsmooth_init ). O código desse filtro fica em $RSFSRC/user/pwd/pwsmooth.c

2020-05-10 15:47 UTC, cauachagas commented
Não sou familiarizado com Madagascar, nunca usei pra falar a verdade. Estou aprendendo a usar o Docker, então usei o repositório como teste. 

### Commit anterior
Eu testei as rotinas de modelagem, inversão e o exemplo de otimização com o Octave. O único problema encontrado foi em [Mhelm2D_fwi.c](https://github.com/brunopdias/semanainvernogeofisica/blob/7f46fac0ea2e3ae5b2d51fed6343f7e154d6e1d6/inversao/helm2D/Mhelm2D_fwi.c#L188). Sem `pwsmooth_init`, consegui rodar o [exemplo](https://github.com/brunopdias/semanainvernogeofisica/blob/master/inversao/shell/commands.sh)

### Novo commit 
Como pedido, olhei `$RSFSRC/user/pwd/pwsmooth.c` e fiz um novo commit.

Mudou de:
```c
pwsmooth_init(radius, n1, n2, 5, 0.01,slope);
```
para:

```c
pwsmooth_init(radius, n1, n2, 5, 0.01);
pwsmooth_set(slope);
```

2020-05-10 15:48 UTC, cauachagas commented
Por acidente, acabei fechando o PR. Desculpe.

2020-05-11 20:06 UTC, brunopdias approved these changes
Valeu Cauã!

2020-05-11 20:07 UTC, merged